name: CI Integration Pipeline (Docker Hub Image)

env:
  user_email: "rauneet.verma@facets.cloud"
  climb_project_name: "testing-prj-1"
  climb-token-dev: ${{ secrets.CLIMB_TOKEN_DEV }}
  service_name: "http-echo"
  backend-image-name: "rauneetverma/http-echo"
  backend-image-tag: "latest"

on:
  push:
    branches:
      - main
      - task/ci-action-test

jobs:
  ci-integration:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: rauneetverma
        password: Rauneet@2000

    - name: Verify Docker image availability
      run: |
        echo "Checking if Docker image exists..."
        docker pull ${{ env.backend-image-name }}:${{ env.backend-image-tag }}

    - name: CI Integration with Facets Climb
      run: |
        curl -sSL https://facets-cloud.github.io/facets-schemas/scripts/fctl_install.sh | bash && source ~/.bashrc
        export PATH="$HOME/facetsctl/bin:$PATH"
        export DOCKER_IMAGE_URL="${{ env.backend-image-name }}:${{ env.backend-image-tag }}"
        export TOKEN="${{ env.climb-token-dev }}"
        export TARGET=dev
        curl -s https://facets-cloud.github.io/facets-schemas/scripts/fctl_register_target.sh | bash -s -- \
          -u ${{ env.user_email }} \
          -c https://facetsdemo.console.facets.cloud \
          -p ${{ env.climb_project_name }} \
          -s ${{ env.service_name }} \
          -a rauneetverma \
          -i "true" \
          -m ENVIRONMENT
